name: FC_Announcer
main: me.Destro168.FC_Announcer.FC_Announcer
version: 5.45
description: Ultimate Automatic Announcement Plugin
commands:
    announcer:
        description: This command turns the plugin on.
        permission: FC_Announcer.admin
depend: [FC_Suite_Shared]